In [1]:
import numpy as np
import warnings
warnings.filterwarnings("ignore")


In [2]:
list1=[10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [3]:
type(list1)

list

In [4]:
arr1=np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [5]:
arr1.data

In [6]:
type(arr1)

numpy.ndarray

In [7]:
print(memoryview(arr1))

In [8]:
arr1.dtype


dtype('int32')

In [9]:
arr1.astype(float)


array([10., 20., 30., 40., 50., 60.])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
 np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [12]:
np.arange(100,0,-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20,  10])

In [13]:
arr3 = np.arange(0,10)
arr3.shape


(10,)

In [14]:
arr3.size


10

In [15]:
arr3.ndim

1

In [16]:
arr3.itemsize

4

In [17]:
arr3.nbytes

40

In [18]:
 np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [19]:
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [20]:
import numpy as np
np.full(5,10)

array([10, 10, 10, 10, 10])

In [21]:
arr1= np.arange(1,20)
arr1[arr1 %2 ==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
np.linspace(10,20,4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [23]:
np.linspace(10,20,11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [24]:
np.random.random(4)

array([0.71423506, 0.08718493, 0.60431844, 0.88957241])

In [25]:
np.random.randint(0,500,5)

array([169,  56, 385, 492,  70])

In [26]:
np.random.randint(0,500,10)

array([ 55, 257, 475, 376, 485, 131, 421, 258, 323, 144])

In [27]:
f1=np.random.uniform(5,10,size=((20)))
f1

array([5.84425678, 6.55173232, 7.25878691, 9.39459951, 7.00420853,
       9.49614421, 6.17711053, 5.97041462, 9.75800277, 9.85956744,
       8.42652296, 8.20086631, 5.62627771, 9.60524632, 8.74953658,
       8.21391152, 7.39513135, 9.89410985, 9.97581081, 7.84253053])

In [28]:
np.floor(f1)

array([5., 6., 7., 9., 7., 9., 6., 5., 9., 9., 8., 8., 5., 9., 8., 8., 7.,
       9., 9., 7.])

In [29]:
np.trunc(f1)

array([5., 6., 7., 9., 7., 9., 6., 5., 9., 9., 8., 8., 5., 9., 8., 8., 7.,
       9., 9., 7.])

In [30]:
f1.astype(int)

array([5, 6, 7, 9, 7, 9, 6, 5, 9, 9, 8, 8, 5, 9, 8, 8, 7, 9, 9, 7])

In [31]:
b2=np.random.randn(10)
b2

array([ 0.92745959,  0.38054021, -0.1590704 ,  1.11872797, -0.50314777,
       -0.56931846, -1.74849294,  1.15800152, -0.35341452,  2.35540991])

In [32]:
arr2=np.arange(1,20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [33]:
arr2.sum()

190

In [34]:
np.cumsum(arr2)#cumulative sum

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [35]:
arr2.min()

1

In [36]:
arr2.max()

19

In [37]:
arr2.mean()

10.0

In [38]:
 np.var(arr2)

30.0

In [39]:
np.std(arr2)

5.477225575051661

In [40]:
import numpy as  np
A= np.array([[1,2,3,0],[5,6,7,22],[10,11,1,13],[14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [41]:
A.sum()


129

In [42]:
np.amin(A, axis =0)

array([1, 2, 1, 0])

In [43]:
np.amin(A,axis=1)  #axis minimum

array([0, 5, 1, 3])

In [44]:
np.std(A) #std = standart deviation = standart sapma


6.348904925260734

In [45]:
for index, value in np.ndenumerate(A):
    print(index, value)
    

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [46]:
import numpy as np
ar= np.arange(1,20)
ar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [47]:
rep1=np.where(ar%2 ==0,0,ar) # even numbers are zero( use to mod 2 )
print(rep1)

[ 1  0  3  0  5  0  7  0  9  0 11  0 13  0 15  0 17  0 19]


In [48]:
ar2=np.array([10,20,30,10,10,20,20])
ar2

array([10, 20, 30, 10, 10, 20, 20])

In [49]:
rep2=np.where (ar2==10,99,ar2)
print(rep2)

[99 20 30 99 99 20 20]


In [50]:
a= np.array([10., np.nan ,20.,30.,60., np.nan,90.,np.inf]) #inf=infinty
a

array([10., nan, 20., 30., 60., nan, 90., inf])

In [51]:
np.isnan(a)

array([False,  True, False, False, False,  True, False, False])

In [52]:
np.where(np.isnan(a))

(array([1, 5], dtype=int64),)

array[1,5] dediği şeyde sadece 1 ve 5 i kastetmiş :)


In [53]:
a[np.isnan(a)]=99
a

array([10., 99., 20., 30., 60., 99., 90., inf])

In [54]:
import numpy as np
A= np.array([[1,2,np.nan,4],[np.nan,6,7,8],[10,np.nan,12,13],[14,15,16,17]])
A


array([[ 1.,  2., nan,  4.],
       [nan,  6.,  7.,  8.],
       [10., nan, 12., 13.],
       [14., 15., 16., 17.]])

In [55]:
a= np.zeros(20).reshape(2,-1)
b= np.repeat(1,20).reshape(2,-1)
a
#a zero point

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [56]:
b # b just ones

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [57]:
np.vstack([a,b]) #ikisi birleşince uniform bir yapı olması için ikisinin sonuna da "." koyuldu 

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [58]:
np.hstack([a,b])

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [59]:
c1= np.array([10,20,30,40,50,60])
c2= np.array ([12,20,33,40,55,60])
np.intersect1d(c1,c2) #ortak elemanları 

array([20, 40, 60])

In [60]:
np.setdiff1d(c1,c2)  #c1 in c2 den farklı olan elemanları kaldı 

array([10, 30, 50])

In [61]:
a4 = np.arange(10,30)
a4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [62]:
a4[::-1] #tersini almak için

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [63]:
np.flip(a4) # tersini almak için

array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

In [64]:
a3= np.array([[1,8,2,3],[70,50,10,67],[45,25,75,15],[12,9,77,4]])
a3

array([[ 1,  8,  2,  3],
       [70, 50, 10, 67],
       [45, 25, 75, 15],
       [12,  9, 77,  4]])

In [65]:
a3[::-1,] #satırların tersini alma

array([[12,  9, 77,  4],
       [45, 25, 75, 15],
       [70, 50, 10, 67],
       [ 1,  8,  2,  3]])

In [66]:
a3[:,::-1] #sütunların tersini alma


array([[ 3,  2,  8,  1],
       [67, 10, 50, 70],
       [15, 75, 25, 45],
       [ 4, 77,  9, 12]])

In [67]:
a3[::-1,::-1]

array([[ 4, 77,  9, 12],
       [15, 75, 25, 45],
       [67, 10, 50, 70],
       [ 3,  2,  8,  1]])

In [68]:
p1=np.arange (0,121).reshape(11,11)
p1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [69]:
np.save("test1.npy",p1)

In [70]:
p2= np.load("test1.npy")
p2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [71]:
np.save("numpyfile.npy",p2)


In [72]:
p3 = np.load("numpyfile.npy")
p3

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20,  21],
       [ 22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32],
       [ 33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43],
       [ 44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
       [ 55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65],
       [ 66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76],
       [ 77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87],
       [ 88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98],
       [ 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]])

In [73]:
p4 = np.arange(0,1000000).reshape(1000,1000)
p4

array([[     0,      1,      2, ...,    997,    998,    999],
       [  1000,   1001,   1002, ...,   1997,   1998,   1999],
       [  2000,   2001,   2002, ...,   2997,   2998,   2999],
       ...,
       [997000, 997001, 997002, ..., 997997, 997998, 997999],
       [998000, 998001, 998002, ..., 998997, 998998, 998999],
       [999000, 999001, 999002, ..., 999997, 999998, 999999]])

In [74]:
np.savez_compressed("test2.npz",p4)

In [75]:
np.save("test3.npy",p4)

In [76]:
from IPython.display import Image

In [77]:
v1 = np.array([1,2])
v2 = np.array([3,4])
v3= v1+v2
print("v3:-",v3)

v3:- [4 6]


In [78]:
p = np.loadtxt("sample.txt",dtype = np.integer)# text dosyası yükleme 
p

array([[24, 29, 88],
       [ 1,  0,  8],
       [33,  7, 99],
       [39, 11, 98],
       [22, 76, 87]])

In [79]:
p5= np.genfromtxt("sample0.txt",dtype="str") #yine text dosyası yükleme
p5

array([['Dogu', 'Turkey', 'Football'],
       ['John', 'USA', 'Hockey'],
       ['Paul', 'Canada', 'Basketball']], dtype='<U10')

In [80]:
np.loadtxt("sample.txt", delimiter = " ", usecols= (0,2))# birbirleri arasında ne ile ayrılmasını istiyorsam falan


array([[24., 88.],
       [ 1.,  8.],
       [33., 99.],
       [39., 98.],
       [22., 87.]])

In [81]:
a1=[5,6,7]
a2=[4,7,9]
print(np.multiply(a1,a2))

[20 42 63]


In [82]:
a1= np.array([1,2,3])
a2= np.array([4,5,6])
dotp = a1@a2
print("Dot product:- ", dotp)

Dot product:-  32


In [83]:
dot= np.dot(a1,a2)
print("Dot product using function :- ", dotp)

Dot product using function :-  32


In [84]:
dotpinner= np.inner(a1,a2)
print(dotpinner)

32


In [85]:
print(sum(np.multiply(a1,a2)))

32


In [86]:
dotp = np.matmul(a1,a2)
print(dotp)

32


In [87]:
dotp=0
for i in range(len(a1)):
    dotp = dotp+ a1[i]*a2[i]
print(dotp)

32


In [88]:
v3 = np.array ([1,2,3,4,5,6])
length = np.sqrt(np.dot(v3,v3))
length

9.539392014169456

In [89]:
#vektör nasıl normalize edilir?
v1=[2,3]
length_v1 = np.sqrt(np.dot(v1,v1))
norm_v1=v1 / length_v1
length_v1, norm_v1


(3.605551275463989, array([0.5547002 , 0.83205029]))

In [90]:
v1=[2,3]
norm_v1 = v1/ np.linalg.norm(v1)
norm_v1

array([0.5547002 , 0.83205029])

In [91]:
np.rad2deg

<ufunc 'rad2deg'>

In [92]:
mat1=np.random.randint(0,1000,100).reshape(10,10)
mat1

array([[521, 402, 953, 547, 254, 749, 236, 932, 276, 912],
       [748, 798, 170, 118, 335, 505, 102, 398, 580, 466],
       [746, 714, 487, 295, 791, 304, 408, 218, 842, 669],
       [123, 682, 889, 543,  10, 737, 585, 680, 911,  62],
       [ 53, 977, 592, 545,  96, 680, 896, 542, 509, 180],
       [456, 980, 765, 689, 233,  93, 420, 602, 638, 877],
       [818, 581, 402, 131, 710, 334, 326, 839, 239, 508],
       [885, 999,  79, 427, 980, 982, 690, 909, 554,  23],
       [926, 337, 284, 580, 416, 668, 820, 370, 302, 448],
       [366, 409, 738, 613, 731, 476, 944, 402, 364, 612]])

In [93]:
 mat1[mat1 >500]

array([521, 953, 547, 749, 932, 912, 748, 798, 505, 580, 746, 714, 791,
       842, 669, 682, 889, 543, 737, 585, 680, 911, 977, 592, 545, 680,
       896, 542, 509, 980, 765, 689, 602, 638, 877, 818, 581, 710, 839,
       508, 885, 999, 980, 982, 690, 909, 554, 926, 580, 668, 820, 738,
       613, 731, 944, 612])

In [94]:
I = np.eye(9) #identity birim matris
I

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [95]:
D = np.diag([1,2,3,4,5,6,7,8]) #diagonal matris
D

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [96]:
M= np.random.randn(5,5)
U=np.triu(M)
L=np.tril(M)
print(M)

[[-0.61169642 -0.54930099  0.09871172  0.76726298 -0.43076816]
 [-0.86953286 -0.98794174  0.0771774   1.2119669  -0.82931179]
 [-0.48464158  0.54992284  2.0331983   0.40229568  0.92801071]
 [-0.5969245  -0.97418569 -0.42030253 -0.47518381  1.67489611]
 [-0.83447848  0.34465581  0.83102705  0.19107613 -0.07563633]]


In [97]:
print(U)

[[-0.61169642 -0.54930099  0.09871172  0.76726298 -0.43076816]
 [ 0.         -0.98794174  0.0771774   1.2119669  -0.82931179]
 [ 0.          0.          2.0331983   0.40229568  0.92801071]
 [ 0.          0.          0.         -0.47518381  1.67489611]
 [ 0.          0.          0.          0.         -0.07563633]]


In [98]:
print(L)

[[-0.61169642  0.          0.          0.          0.        ]
 [-0.86953286 -0.98794174  0.          0.          0.        ]
 [-0.48464158  0.54992284  2.0331983   0.          0.        ]
 [-0.5969245  -0.97418569 -0.42030253 -0.47518381  0.        ]
 [-0.83447848  0.34465581  0.83102705  0.19107613 -0.07563633]]


In [99]:
M=np.array([[1,2,3],[4,-3,6],[7,8,0]])
print(M)

[[ 1  2  3]
 [ 4 -3  6]
 [ 7  8  0]]


In [100]:
np.transpose(M) #transpose alma 

array([[ 1,  4,  7],
       [ 2, -3,  8],
       [ 3,  6,  0]])

In [101]:
M.T  #transpose alma 

array([[ 1,  4,  7],
       [ 2, -3,  8],
       [ 3,  6,  0]])

In [102]:
#determinant bulma
np.linalg.det(M)

195.0

In [103]:
np.linalg.inv(M) #inverse alma 

array([[-0.24615385,  0.12307692,  0.10769231],
       [ 0.21538462, -0.10769231,  0.03076923],
       [ 0.27179487,  0.03076923, -0.05641026]])

In [104]:
N= np.array([[1,1,1],[2,2,2],[3,3,3]]) #bölme
print(M/N)

[[ 1.          2.          3.        ]
 [ 2.         -1.5         3.        ]
 [ 2.33333333  2.66666667  0.        ]]


In [105]:
np.divide(M,N) #bölme

array([[ 1.        ,  2.        ,  3.        ],
       [ 2.        , -1.5       ,  3.        ],
       [ 2.33333333,  2.66666667,  0.        ]])

In [106]:
M1= np.array([[1,2],[4,5]])
M1

array([[1, 2],
       [4, 5]])

In [107]:
M1@M1@M1 #3. kuvvetini alma

array([[ 57,  78],
       [156, 213]])

In [108]:
np.linalg.matrix_power (M1,3) #kuvvet alma

array([[ 57,  78],
       [156, 213]])

In [109]:
#tensör,upgraded matrix
T1=np.array([
    [[1,2,3],[4,5,6],[7,8,9]],
[[10,20,30],[40,50,60],[70,80,90]],
[[100,200,300],[400,500,600],[700,800,900]]])

T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [110]:
T2= np.array([
    [[0,0,0],[0,0,0],[0,0,0]],
    [[1,1,1],[1,1,1],[1,1,1]],
    [[2,2,2],[2,2,2],[2,2,2]]
    ])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [111]:
D = T1/T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [112]:
A = T1+T2
A


array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])